var vscodeIconsValid = {
  "3d": "assets/vscode-icons/icons/3d.svg",
  "abc": "assets/vscode-icons/icons/abc.svg",
  "actionscript": "assets/vscode-icons/icons/actionscript.svg",
  "ada": "assets/vscode-icons/icons/ada.svg",
  "adonis": "assets/vscode-icons/icons/adonis.svg",
  "advpl_include": "assets/vscode-icons/icons/advpl_include.svg",
  "advpl_prw": "assets/vscode-icons/icons/advpl_prw.svg",
  "advpl_ptm": "assets/vscode-icons/icons/advpl_ptm.svg",
  "advpl_tlpp": "assets/vscode-icons/icons/advpl_tlpp.svg",
  "ai": "assets/vscode-icons/icons/ai.svg",
  "android": "assets/vscode-icons/icons/android.svg",
  "angular-component": "assets/vscode-icons/icons/angular-component",
  "angular-directive": "assets/vscode-icons/icons/angular-directive",
  "angular-guard": "assets/vscode-icons/icons/angular-guard",
  "angular-pipe": "assets/vscode-icons/icons/angular-pipe",
  "angular-resolver": "assets/vscode-icons/icons/angular-resolver",
  "angular-service": "assets/vscode-icons/icons/angular-service",
  "angular": "assets/vscode-icons/icons/angular.svg",
  "apiblueprint": "assets/vscode-icons/icons/apiblueprint.svg",
  "apollo": "assets/vscode-icons/icons/apollo.svg",
  "applescript": "assets/vscode-icons/icons/applescript.svg",
  "appveyor": "assets/vscode-icons/icons/appveyor.svg",
  "arduino": "assets/vscode-icons/icons/arduino.svg",
  "asciidoc": "assets/vscode-icons/icons/asciidoc.svg",
  "assembly": "assets/vscode-icons/icons/assembly.svg",
  "astro": "assets/vscode-icons/icons/astro.svg",
  "astyle": "assets/vscode-icons/icons/astyle.svg",
  "audio": "assets/vscode-icons/icons/audio.svg",
  "aurelia": "assets/vscode-icons/icons/aurelia.svg",
  "authors": "assets/vscode-icons/icons/authors.svg",
  "autohotkey": "assets/vscode-icons/icons/autohotkey.svg",
  "autoit": "assets/vscode-icons/icons/autoit.svg",
  "auto": "assets/vscode-icons/icons/auto.svg",
  "azure-pipelines": "assets/vscode-icons/icons/azure-pipelines",
  "azure": "assets/vscode-icons/icons/azure.svg",
  "babel": "assets/vscode-icons/icons/babel.svg",
  "ballerina": "assets/vscode-icons/icons/ballerina.svg",
  "bat": "assets/vscode-icons/icons/bat.svg",
  "bazel": "assets/vscode-icons/icons/bazel.svg",
  "bicep": "assets/vscode-icons/icons/bicep.svg",
  "bitbucket": "assets/vscode-icons/icons/bitbucket.svg",
  "bithound": "assets/vscode-icons/icons/bithound.svg",
  "blade": "assets/vscode-icons/icons/blade.svg",
  "blink": "assets/vscode-icons/icons/blink.svg",
  "blitz": "assets/vscode-icons/icons/blitz.svg",
  "bower": "assets/vscode-icons/icons/bower.svg",
  "brainfuck": "assets/vscode-icons/icons/brainfuck.svg",
  "browserslist": "assets/vscode-icons/icons/browserslist.svg",
  "bucklescript": "assets/vscode-icons/icons/bucklescript.svg",
  "buck": "assets/vscode-icons/icons/buck.svg",
  "buildkite": "assets/vscode-icons/icons/buildkite.svg",
  "bundler": "assets/vscode-icons/icons/bundler.svg",
  "cabal": "assets/vscode-icons/icons/cabal.svg",
  "cake": "assets/vscode-icons/icons/cake.svg",
  "capacitor": "assets/vscode-icons/icons/capacitor.svg",
  "certificate": "assets/vscode-icons/icons/certificate.svg",
  "changelog": "assets/vscode-icons/icons/changelog.svg",
  "chess": "assets/vscode-icons/icons/chess.svg",
  "circleci": "assets/vscode-icons/icons/circleci.svg",
  "clojure": "assets/vscode-icons/icons/clojure.svg",
  "cloudfoundry": "assets/vscode-icons/icons/cloudfoundry.svg",
  "cmake": "assets/vscode-icons/icons/cmake.svg",
  "coala": "assets/vscode-icons/icons/coala.svg",
  "cobol": "assets/vscode-icons/icons/cobol.svg",
  "coconut": "assets/vscode-icons/icons/coconut.svg",
  "code-climate": "assets/vscode-icons/icons/code-climate",
  "codecov": "assets/vscode-icons/icons/codecov.svg",
  "codeowners": "assets/vscode-icons/icons/codeowners.svg",
  "coffee": "assets/vscode-icons/icons/coffee.svg",
  "coldfusion": "assets/vscode-icons/icons/coldfusion.svg",
  "command": "assets/vscode-icons/icons/command.svg",
  "commitlint": "assets/vscode-icons/icons/commitlint.svg",
  "compodoc": "assets/vscode-icons/icons/compodoc.svg",
  "conduct": "assets/vscode-icons/icons/conduct.svg",
  "console": "assets/vscode-icons/icons/console.svg",
  "contributing": "assets/vscode-icons/icons/contributing.svg",
  "cpp": "assets/vscode-icons/icons/cpp.svg",
  "credits": "assets/vscode-icons/icons/credits.svg",
  "crystal": "assets/vscode-icons/icons/crystal.svg",
  "csharp": "assets/vscode-icons/icons/csharp.svg",
  "cssmap": "assets/vscode-icons/icons/cssmap.svg",
  "css": "assets/vscode-icons/icons/css.svg",
  "c": "assets/vscode-icons/icons/c.svg",
  "csv": "assets/vscode-icons/icons/csv.svg",
  "cucumber": "assets/vscode-icons/icons/cucumber.svg",
  "cuda": "assets/vscode-icons/icons/cuda.svg",
  "cypress": "assets/vscode-icons/icons/cypress.svg",
  "dart": "assets/vscode-icons/icons/dart.svg",
  "database": "assets/vscode-icons/icons/database.svg",
  "denizenscript": "assets/vscode-icons/icons/denizenscript.svg",
  "deno": "assets/vscode-icons/icons/deno.svg",
  "dependabot": "assets/vscode-icons/icons/dependabot.svg",
  "dhall": "assets/vscode-icons/icons/dhall.svg",
  "dinophp": "assets/vscode-icons/icons/dinophp.svg",
  "disc": "assets/vscode-icons/icons/disc.svg",
  "django": "assets/vscode-icons/icons/django.svg",
  "docker": "assets/vscode-icons/icons/docker.svg",
  "document": "assets/vscode-icons/icons/document.svg",
  "dotjs": "assets/vscode-icons/icons/dotjs.svg",
  "drawio": "assets/vscode-icons/icons/drawio.svg",
  "drone": "assets/vscode-icons/icons/drone.svg",
  "d": "assets/vscode-icons/icons/d.svg",
  "dune": "assets/vscode-icons/icons/dune.svg",
  "edge": "assets/vscode-icons/icons/edge.svg",
  "editorconfig": "assets/vscode-icons/icons/editorconfig.svg",
  "eex": "assets/vscode-icons/icons/eex.svg",
  "ejs": "assets/vscode-icons/icons/ejs.svg",
  "elixir": "assets/vscode-icons/icons/elixir.svg",
  "elm": "assets/vscode-icons/icons/elm.svg",
  "email": "assets/vscode-icons/icons/email.svg",
  "ember": "assets/vscode-icons/icons/ember.svg",
  "env": "assets/vscode-icons/icons/env.svg",
  "erlang": "assets/vscode-icons/icons/erlang.svg",
  "eslint": "assets/vscode-icons/icons/eslint.svg",
  "exe": "assets/vscode-icons/icons/exe.svg",
  "fastlane": "assets/vscode-icons/icons/fastlane.svg",
  "favicon": "assets/vscode-icons/icons/favicon.svg",
  "figma": "assets/vscode-icons/icons/figma.svg",
  "file": "assets/vscode-icons/icons/file.svg",
  "firebase": "assets/vscode-icons/icons/firebase.svg",
  "flash": "assets/vscode-icons/icons/flash.svg",
  "flow": "assets/vscode-icons/icons/flow.svg",
  "folder_admin_open": "assets/vscode-icons/icons/folder_admin_open.svg",
  "folder_admin": "assets/vscode-icons/icons/folder_admin.svg",
  "folder_android_open": "assets/vscode-icons/icons/folder_android_open.svg",
  "folder_android": "assets/vscode-icons/icons/folder_android.svg",
  "folder_angular_open": "assets/vscode-icons/icons/folder_angular_open.svg",
  "folder_angular": "assets/vscode-icons/icons/folder_angular.svg",
  "folder_animation_open":
      "assets/vscode-icons/icons/folder_animation_open.svg",
  "folder_animation": "assets/vscode-icons/icons/folder_animation.svg",
  "folder_animations_open":
      "assets/vscode-icons/icons/folder_animation_open.svg",
  "folder_animations": "assets/vscode-icons/icons/folder_animation.svg",
  "folder_ansible_open": "assets/vscode-icons/icons/folder_ansible_open.svg",
  "folder_ansible": "assets/vscode-icons/icons/folder_ansible.svg",
  "folder_api_open": "assets/vscode-icons/icons/folder_api_open.svg",
  "folder_api": "assets/vscode-icons/icons/folder_api.svg",
  "folder_apis_open": "assets/vscode-icons/icons/folder_api_open.svg",
  "folder_apis": "assets/vscode-icons/icons/folder_api.svg",
  "folder_apollo_open": "assets/vscode-icons/icons/folder_apollo_open.svg",
  "folder_apollo": "assets/vscode-icons/icons/folder_apollo.svg",
  "folder_app_open": "assets/vscode-icons/icons/folder_app_open.svg",
  "folder_app": "assets/vscode-icons/icons/folder_app.svg",
  "folder_apps_open": "assets/vscode-icons/icons/folder_app_open.svg",
  "folder_apps": "assets/vscode-icons/icons/folder_app.svg",
  "folder_archive_open": "assets/vscode-icons/icons/folder_archive_open.svg",
  "folder_archive": "assets/vscode-icons/icons/folder_archive.svg",
  "folder_archives_open": "assets/vscode-icons/icons/folder_archive_open.svg",
  "folder_archives": "assets/vscode-icons/icons/folder_archive.svg",
  "folder_asset_open": "assets/vscode-icons/icons/folder_asset_open.svg",
  "folder_asset": "assets/vscode-icons/icons/folder_asset.svg",
  "folder_assets_open": "assets/vscode-icons/icons/folder_asset_open.svg",
  "folder_assets": "assets/vscode-icons/icons/folder_asset.svg",
  "folder_audio_open": "assets/vscode-icons/icons/folder_audio_open.svg",
  "folder_audio": "assets/vscode-icons/icons/folder_audio.svg",
  "folder_aurelia_open": "assets/vscode-icons/icons/folder_aurelia_open.svg",
  "folder_aurelia": "assets/vscode-icons/icons/folder_aurelia.svg",
  "folder_aws_open": "assets/vscode-icons/icons/folder_aws_open.svg",
  "folder_aws": "assets/vscode-icons/icons/folder_aws.svg",
  "folder_azure_pipelines_open":
      "assets/vscode-icons/icons/folder_azure_pipelines_open.svg",
  "folder_azure_pipelines":
      "assets/vscode-icons/icons/folder_azure_pipelines.svg",
  "folder_base_open": "assets/vscode-icons/icons/folder_base_open.svg",
  "folder_base": "assets/vscode-icons/icons/folder_base.svg",
  "folder_batch_open": "assets/vscode-icons/icons/folder_batch_open.svg",
  "folder_batch": "assets/vscode-icons/icons/folder_batch.svg",
  "folder_benchmark_open":
      "assets/vscode-icons/icons/folder_benchmark_open.svg",
  "folder_benchmark": "assets/vscode-icons/icons/folder_benchmark.svg",
  "folder_bower_open": "assets/vscode-icons/icons/folder_bower_open.svg",
  "folder_bower": "assets/vscode-icons/icons/folder_bower.svg",
  "folder_cart_open": "assets/vscode-icons/icons/folder_cart_open.svg",
  "folder_cart": "assets/vscode-icons/icons/folder_cart.svg",
  "folder_changesets_open":
      "assets/vscode-icons/icons/folder_changesets_open.svg",
  "folder_changesets": "assets/vscode-icons/icons/folder_changesets.svg",
  "folder_ci_open": "assets/vscode-icons/icons/folder_ci_open.svg",
  "folder_circleci_open": "assets/vscode-icons/icons/folder_circleci_open.svg",
  "folder_circleci": "assets/vscode-icons/icons/folder_circleci.svg",
  "folder_ci": "assets/vscode-icons/icons/folder_ci.svg",
  "folder_client_open": "assets/vscode-icons/icons/folder_client_open.svg",
  "folder_client": "assets/vscode-icons/icons/folder_client.svg",
  "folder_clients_open": "assets/vscode-icons/icons/folder_client_open.svg",
  "folder_clients": "assets/vscode-icons/icons/folder_client.svg",
  "folder_cluster_open": "assets/vscode-icons/icons/folder_cluster_open.svg",
  "folder_cluster": "assets/vscode-icons/icons/folder_cluster.svg",
  "folder_cobol_open": "assets/vscode-icons/icons/folder_cobol_open.svg",
  "folder_cobol": "assets/vscode-icons/icons/folder_cobol.svg",
  "folder_command_open": "assets/vscode-icons/icons/folder_command_open.svg",
  "folder_command": "assets/vscode-icons/icons/folder_command.svg",
  "folder_commands_open": "assets/vscode-icons/icons/folder_command_open.svg",
  "folder_commands": "assets/vscode-icons/icons/folder_command.svg",
  "folder_component_open":
      "assets/vscode-icons/icons/folder_component_open.svg",
  "folder_component": "assets/vscode-icons/icons/folder_component.svg",
  "folder_components_open":
      "assets/vscode-icons/icons/folder_component_open.svg",
  "folder_components": "assets/vscode-icons/icons/folder_component.svg",
  "folder_config_open": "assets/vscode-icons/icons/folder_config_open.svg",
  "folder_config": "assets/vscode-icons/icons/folder_config.svg",
  "folder_configs_open": "assets/vscode-icons/icons/folder_config_open.svg",
  "folder_configs": "assets/vscode-icons/icons/folder_config.svg",
  "folder_connection_open":
      "assets/vscode-icons/icons/folder_connection_open.svg",
  "folder_connection": "assets/vscode-icons/icons/folder_connection.svg",
  "folder_connections_open":
      "assets/vscode-icons/icons/folder_connection_open.svg",
  "folder_connections": "assets/vscode-icons/icons/folder_connection.svg",
  "folder_constant_open": "assets/vscode-icons/icons/folder_constant_open.svg",
  "folder_constant": "assets/vscode-icons/icons/folder_constant.svg",
  "folder_constants_open": "assets/vscode-icons/icons/folder_constant_open.svg",
  "folder_constants": "assets/vscode-icons/icons/folder_constant.svg",
  "folder_container_open":
      "assets/vscode-icons/icons/folder_container_open.svg",
  "folder_container": "assets/vscode-icons/icons/folder_container.svg",
  "folder_containers_open":
      "assets/vscode-icons/icons/folder_container_open.svg",
  "folder_containers": "assets/vscode-icons/icons/folder_container.svg",
  "folder_content_open": "assets/vscode-icons/icons/folder_content_open.svg",
  "folder_content": "assets/vscode-icons/icons/folder_content.svg",
  "folder_context_open": "assets/vscode-icons/icons/folder_context_open.svg",
  "folder_context": "assets/vscode-icons/icons/folder_context.svg",
  "folder_contract_open": "assets/vscode-icons/icons/folder_contract_open.svg",
  "folder_contract": "assets/vscode-icons/icons/folder_contract.svg",
  "folder_contracts_open": "assets/vscode-icons/icons/folder_contract_open.svg",
  "folder_contracts": "assets/vscode-icons/icons/folder_contract.svg",
  "folder_controller_open":
      "assets/vscode-icons/icons/folder_controller_open.svg",
  "folder_controller": "assets/vscode-icons/icons/folder_controller.svg",
  "folder_controllers_open":
      "assets/vscode-icons/icons/folder_controller_open.svg",
  "folder_controllers": "assets/vscode-icons/icons/folder_controller.svg",
  "folder_core_open": "assets/vscode-icons/icons/folder_core_open.svg",
  "folder_core": "assets/vscode-icons/icons/folder_core.svg",
  "folder_coverage_open": "assets/vscode-icons/icons/folder_coverage_open.svg",
  "folder_coverage": "assets/vscode-icons/icons/folder_coverage.svg",
  "folder_css_open": "assets/vscode-icons/icons/folder_css_open.svg",
  "folder_css": "assets/vscode-icons/icons/folder_css.svg",
  "folder_custom_open": "assets/vscode-icons/icons/folder_custom_open.svg",
  "folder_custom": "assets/vscode-icons/icons/folder_custom.svg",
  "folder_cypress_open": "assets/vscode-icons/icons/folder_cypress_open.svg",
  "folder_cypress": "assets/vscode-icons/icons/folder_cypress.svg",
  "folder_database_open": "assets/vscode-icons/icons/folder_database_open.svg",
  "folder_database": "assets/vscode-icons/icons/folder_database.svg",
  "folder_databases_open": "assets/vscode-icons/icons/folder_database_open.svg",
  "folder_databases": "assets/vscode-icons/icons/folder_database.svg",
  "folder_debug_open": "assets/vscode-icons/icons/folder_debug_open.svg",
  "folder_debug": "assets/vscode-icons/icons/folder_debug.svg",
  "folder_delta_open": "assets/vscode-icons/icons/folder_delta_open.svg",
  "folder_delta": "assets/vscode-icons/icons/folder_delta.svg",
  "folder_dist_open": "assets/vscode-icons/icons/folder_dist_open.svg",
  "folder_dist": "assets/vscode-icons/icons/folder_dist.svg",
  "folder_docker_open": "assets/vscode-icons/icons/folder_docker_open.svg",
  "folder_docker": "assets/vscode-icons/icons/folder_docker.svg",
  "folder_doc_open": "assets/vscode-icons/icons/folder_docs_open.svg",
  "folder_doc": "assets/vscode-icons/icons/folder_docs.svg",
  "folder_docs_open": "assets/vscode-icons/icons/folder_docs_open.svg",
  "folder_docs": "assets/vscode-icons/icons/folder_docs.svg",
  "folder_download_open": "assets/vscode-icons/icons/folder_download_open.svg",
  "folder_download": "assets/vscode-icons/icons/folder_download.svg",
  "folder_downloads_open": "assets/vscode-icons/icons/folder_download_open.svg",
  "folder_downloads": "assets/vscode-icons/icons/folder_download.svg",
  "folder_dump_open": "assets/vscode-icons/icons/folder_dump_open.svg",
  "folder_dump": "assets/vscode-icons/icons/folder_dump.svg",
  "folder_environment_open":
      "assets/vscode-icons/icons/folder_environment_open.svg",
  "folder_environment": "assets/vscode-icons/icons/folder_environment.svg",
  "folder_env_open": "assets/vscode-icons/icons/folder_environment_open.svg",
  "folder_env": "assets/vscode-icons/icons/folder_environment.svg",
  "folder_environments_open":
      "assets/vscode-icons/icons/folder_environment_open.svg",
  "folder_environments": "assets/vscode-icons/icons/folder_environment.svg",
  "folder_error_open": "assets/vscode-icons/icons/folder_error_open.svg",
  "folder_error": "assets/vscode-icons/icons/folder_error.svg",
  "folder_event_open": "assets/vscode-icons/icons/folder_event_open.svg",
  "folder_event": "assets/vscode-icons/icons/folder_event.svg",
  "folder_events_open": "assets/vscode-icons/icons/folder_event_open.svg",
  "folder_events": "assets/vscode-icons/icons/folder_event.svg",
  "folder_example_open": "assets/vscode-icons/icons/folder_examples_open.svg",
  "folder_example": "assets/vscode-icons/icons/folder_examples.svg",
  "folder_examples_open": "assets/vscode-icons/icons/folder_examples_open.svg",
  "folder_examples": "assets/vscode-icons/icons/folder_examples.svg",
  "folder_expo_open": "assets/vscode-icons/icons/folder_expo_open.svg",
  "folder_expo": "assets/vscode-icons/icons/folder_expo.svg",
  "folder_export_open": "assets/vscode-icons/icons/folder_export_open.svg",
  "folder_export": "assets/vscode-icons/icons/folder_export.svg",
  "folder_exports_open": "assets/vscode-icons/icons/folder_export_open.svg",
  "folder_exports": "assets/vscode-icons/icons/folder_export.svg",
  "folder_fastlane_open": "assets/vscode-icons/icons/folder_fastlane_open.svg",
  "folder_fastlane": "assets/vscode-icons/icons/folder_fastlane.svg",
  "folder_firebase_open": "assets/vscode-icons/icons/folder_firebase_open.svg",
  "folder_firebase": "assets/vscode-icons/icons/folder_firebase.svg",
  "folder_flow_open": "assets/vscode-icons/icons/folder_flow_open.svg",
  "folder_flow": "assets/vscode-icons/icons/folder_flow.svg",
  "folder_flows_open": "assets/vscode-icons/icons/folder_flow_open.svg",
  "folder_flows": "assets/vscode-icons/icons/folder_flow.svg",
  "folder_font_open": "assets/vscode-icons/icons/folder_fonts_open.svg",
  "folder_font": "assets/vscode-icons/icons/folder_fonts.svg",
  "folder_fonts_open": "assets/vscode-icons/icons/folder_fonts_open.svg",
  "folder_fonts": "assets/vscode-icons/icons/folder_fonts.svg",
  "folder_functions_open":
      "assets/vscode-icons/icons/folder_functions_open.svg",
  "folder_functions": "assets/vscode-icons/icons/folder_functions.svg",
  "folder_generator_open":
      "assets/vscode-icons/icons/folder_generator_open.svg",
  "folder_generator": "assets/vscode-icons/icons/folder_generator.svg",
  "folder_github_open": "assets/vscode-icons/icons/folder_github_open.svg",
  "folder_github": "assets/vscode-icons/icons/folder_github.svg",
  "folder_gitlab_open": "assets/vscode-icons/icons/folder_gitlab_open.svg",
  "folder_gitlab": "assets/vscode-icons/icons/folder_gitlab.svg",
  "folder_git_open": "assets/vscode-icons/icons/folder_git_open.svg",
  "folder_git": "assets/vscode-icons/icons/folder_git.svg",
  "folder_global_open": "assets/vscode-icons/icons/folder_global_open.svg",
  "folder_global": "assets/vscode-icons/icons/folder_global.svg",
  "folder_gradle_open": "assets/vscode-icons/icons/folder_gradle_open.svg",
  "folder_gradle": "assets/vscode-icons/icons/folder_gradle.svg",
  "folder_graphql_open": "assets/vscode-icons/icons/folder_graphql_open.svg",
  "folder_graphql": "assets/vscode-icons/icons/folder_graphql.svg",
  "folder_guard_open": "assets/vscode-icons/icons/folder_guard_open.svg",
  "folder_guard": "assets/vscode-icons/icons/folder_guard.svg",
  "folder_gulp_open": "assets/vscode-icons/icons/folder_gulp_open.svg",
  "folder_gulp": "assets/vscode-icons/icons/folder_gulp.svg",
  "folder_helper_open": "assets/vscode-icons/icons/folder_helper_open.svg",
  "folder_helper": "assets/vscode-icons/icons/folder_helper.svg",
  "folder_helpers_open": "assets/vscode-icons/icons/folder_helper_open.svg",
  "folder_helpers": "assets/vscode-icons/icons/folder_helper.svg",
  "folder_home_open": "assets/vscode-icons/icons/folder_home_open.svg",
  "folder_home": "assets/vscode-icons/icons/folder_home.svg",
  "folder_hook_open": "assets/vscode-icons/icons/folder_hook_open.svg",
  "folder_hook": "assets/vscode-icons/icons/folder_hook.svg",
  "folder_husky_open": "assets/vscode-icons/icons/folder_husky_open.svg",
  "folder_husky": "assets/vscode-icons/icons/folder_husky.svg",
  "folder_i18n_open": "assets/vscode-icons/icons/folder_i18n_open.svg",
  "folder_i18n": "assets/vscode-icons/icons/folder_i18n.svg",
  "folder_image_open": "assets/vscode-icons/icons/folder_images_open.svg",
  "folder_image": "assets/vscode-icons/icons/folder_images.svg",
  "folder_images_open": "assets/vscode-icons/icons/folder_images_open.svg",
  "folder_images": "assets/vscode-icons/icons/folder_images.svg",
  "folder_import_open": "assets/vscode-icons/icons/folder_import_open.svg",
  "folder_import": "assets/vscode-icons/icons/folder_import.svg",
  "folder_imports_open": "assets/vscode-icons/icons/folder_import_open.svg",
  "folder_imports": "assets/vscode-icons/icons/folder_import.svg",
  "folder_include_open": "assets/vscode-icons/icons/folder_include_open.svg",
  "folder_include": "assets/vscode-icons/icons/folder_include.svg",
  "folder_intellij_open": "assets/vscode-icons/icons/folder_intellij_open.svg",
  "folder_intellij": "assets/vscode-icons/icons/folder_intellij.svg",
  "folder_interface_open":
      "assets/vscode-icons/icons/folder_interface_open.svg",
  "folder_interface": "assets/vscode-icons/icons/folder_interface.svg",
  "folder_interfaces_open":
      "assets/vscode-icons/icons/folder_interface_open.svg",
  "folder_interfaces": "assets/vscode-icons/icons/folder_interface.svg",
  "folder_ios_open": "assets/vscode-icons/icons/folder_ios_open.svg",
  "folder_ios": "assets/vscode-icons/icons/folder_ios.svg",
  "folder_javascript_open":
      "assets/vscode-icons/icons/folder_javascript_open.svg",
  "folder_javascript": "assets/vscode-icons/icons/folder_javascript.svg",
  "folder_jinja_open": "assets/vscode-icons/icons/folder_jinja_open.svg",
  "folder_jinja": "assets/vscode-icons/icons/folder_jinja.svg",
  "folder_job_open": "assets/vscode-icons/icons/folder_job_open.svg",
  "folder_job": "assets/vscode-icons/icons/folder_job.svg",
  "folder_jobs_open": "assets/vscode-icons/icons/folder_job_open.svg",
  "folder_jobs": "assets/vscode-icons/icons/folder_job.svg",
  "folder_json_open": "assets/vscode-icons/icons/folder_json_open.svg",
  "folder_json": "assets/vscode-icons/icons/folder_json.svg",
  "folder_jsons_open": "assets/vscode-icons/icons/folder_json_open.svg",
  "folder_jsons": "assets/vscode-icons/icons/folder_json.svg",
  "folder_jwt_open": "assets/vscode-icons/icons/folder_jwt_open.svg",
  "folder_jwt": "assets/vscode-icons/icons/folder_jwt.svg",
  "folder_key_open": "assets/vscode-icons/icons/folder_keys_open.svg",
  "folder_key": "assets/vscode-icons/icons/folder_keys.svg",
  "folder_keys_open": "assets/vscode-icons/icons/folder_keys_open.svg",
  "folder_keys": "assets/vscode-icons/icons/folder_keys.svg",
  "folder_kubernetes_open":
      "assets/vscode-icons/icons/folder_kubernetes_open.svg",
  "folder_kubernetes": "assets/vscode-icons/icons/folder_kubernetes.svg",
  "folder_layout_open": "assets/vscode-icons/icons/folder_layout_open.svg",
  "folder_layout": "assets/vscode-icons/icons/folder_layout.svg",
  "folder_layouts_open": "assets/vscode-icons/icons/folder_layout_open.svg",
  "folder_layouts": "assets/vscode-icons/icons/folder_layout.svg",
  "folder_less_open": "assets/vscode-icons/icons/folder_less_open.svg",
  "folder_less": "assets/vscode-icons/icons/folder_less.svg",
  "folder_library_open": "assets/vscode-icons/icons/folder_library_open.svg",
  "folder_library": "assets/vscode-icons/icons/folder_library.svg",
  "folder_libraries_open": "assets/vscode-icons/icons/folder_library_open.svg",
  "folder_libraries": "assets/vscode-icons/icons/folder_library.svg",
  "folder_log_open": "assets/vscode-icons/icons/folder_log_open.svg",
  "folder_log": "assets/vscode-icons/icons/folder_log.svg",
  "folder_logs_open": "assets/vscode-icons/icons/folder_log_open.svg",
  "folder_logs": "assets/vscode-icons/icons/folder_log.svg",
  "folder_lua_open": "assets/vscode-icons/icons/folder_lua_open.svg",
  "folder_lua": "assets/vscode-icons/icons/folder_lua.svg",
  "folder_mail_open": "assets/vscode-icons/icons/folder_mail_open.svg",
  "folder_mail": "assets/vscode-icons/icons/folder_mail.svg",
  "folder_mails_open": "assets/vscode-icons/icons/folder_mail_open.svg",
  "folder_mails": "assets/vscode-icons/icons/folder_mail.svg",
  "folder_mappings_open": "assets/vscode-icons/icons/folder_mappings_open.svg",
  "folder_mappings": "assets/vscode-icons/icons/folder_mappings.svg",
  "folder_markdown_open": "assets/vscode-icons/icons/folder_markdown_open.svg",
  "folder_markdown": "assets/vscode-icons/icons/folder_markdown.svg",
  "folder_messages_open": "assets/vscode-icons/icons/folder_messages_open.svg",
  "folder_messages": "assets/vscode-icons/icons/folder_messages.svg",
  "folder_meta_open": "assets/vscode-icons/icons/folder_meta_open.svg",
  "folder_meta": "assets/vscode-icons/icons/folder_meta.svg",
  "folder_middleware_open":
      "assets/vscode-icons/icons/folder_middleware_open.svg",
  "folder_middleware": "assets/vscode-icons/icons/folder_middleware.svg",
  "folder_middlewares_open":
      "assets/vscode-icons/icons/folder_middleware_open.svg",
  "folder_middlewares": "assets/vscode-icons/icons/folder_middleware.svg",
  "folder_migration_open":
      "assets/vscode-icons/icons/folder_migration_open.svg",
  "folder_migration": "assets/vscode-icons/icons/folder_migration.svg",
  "folder_migrations_open":
      "assets/vscode-icons/icons/folder_migration_open.svg",
  "folder_migrations": "assets/vscode-icons/icons/folder_migration.svg",
  "folder_mjml_open": "assets/vscode-icons/icons/folder_mjml_open.svg",
  "folder_mjml": "assets/vscode-icons/icons/folder_mjml.svg",
  "folder_mobile_open": "assets/vscode-icons/icons/folder_mobile_open.svg",
  "folder_mobile": "assets/vscode-icons/icons/folder_mobile.svg",
  "folder_mock_open": "assets/vscode-icons/icons/folder_mock_open.svg",
  "folder_mock": "assets/vscode-icons/icons/folder_mock.svg",
  "folder_model_open": "assets/vscode-icons/icons/folder_model_open.svg",
  "folder_model": "assets/vscode-icons/icons/folder_model.svg",
  "folder_models_open": "assets/vscode-icons/icons/folder_model_open.svg",
  "folder_models": "assets/vscode-icons/icons/folder_model.svg",
  "folder_next_open": "assets/vscode-icons/icons/folder_next_open.svg",
  "folder_next": "assets/vscode-icons/icons/folder_next.svg",
  "folder_node_open": "assets/vscode-icons/icons/folder_node_open.svg",
  "folder_node": "assets/vscode-icons/icons/folder_node.svg",
  "folder_node_modules_open": "assets/vscode-icons/icons/folder_node_open.svg",
  "folder_node_modules": "assets/vscode-icons/icons/folder_node.svg",
  "folder_nuxt_open": "assets/vscode-icons/icons/folder_nuxt_open.svg",
  "folder_nuxt": "assets/vscode-icons/icons/folder_nuxt.svg",
  "folder_other_open": "assets/vscode-icons/icons/folder_other_open.svg",
  "folder_other": "assets/vscode-icons/icons/folder_other.svg",
  "folder_package_open": "assets/vscode-icons/icons/folder_package_open.svg",
  "folder_package": "assets/vscode-icons/icons/folder_package.svg",
  "folder_packages_open": "assets/vscode-icons/icons/folder_package_open.svg",
  "folder_packages": "assets/vscode-icons/icons/folder_package.svg",
  "folder_phpmailer_open":
      "assets/vscode-icons/icons/folder_phpmailer_open.svg",
  "folder_phpmailer": "assets/vscode-icons/icons/folder_phpmailer.svg",
  "folder_php_open": "assets/vscode-icons/icons/folder_php_open.svg",
  "folder_php": "assets/vscode-icons/icons/folder_php.svg",
  "folder_pipe_open": "assets/vscode-icons/icons/folder_pipe_open.svg",
  "folder_pipe": "assets/vscode-icons/icons/folder_pipe.svg",
  "folder_playwright_open":
      "assets/vscode-icons/icons/folder_playwright_open.svg",
  "folder_playwright": "assets/vscode-icons/icons/folder_playwright.svg",
  "folder_plugin_open": "assets/vscode-icons/icons/folder_plugin_open.svg",
  "folder_plugin": "assets/vscode-icons/icons/folder_plugin.svg",
  "folder_plugins_open": "assets/vscode-icons/icons/folder_plugin_open.svg",
  "folder_plugins": "assets/vscode-icons/icons/folder_plugin.svg",
  "folder_prisma_open": "assets/vscode-icons/icons/folder_prisma_open.svg",
  "folder_prisma": "assets/vscode-icons/icons/folder_prisma.svg",
  "folder_private_open": "assets/vscode-icons/icons/folder_private_open.svg",
  "folder_private": "assets/vscode-icons/icons/folder_private.svg",
  "folder_project_open": "assets/vscode-icons/icons/folder_project_open.svg",
  "folder_project": "assets/vscode-icons/icons/folder_project.svg",
  "folder_public_open": "assets/vscode-icons/icons/folder_public_open.svg",
  "folder_public": "assets/vscode-icons/icons/folder_public.svg",
  "folder_python_open": "assets/vscode-icons/icons/folder_python_open.svg",
  "folder_python": "assets/vscode-icons/icons/folder_python.svg",
  "folder_quasar_open": "assets/vscode-icons/icons/folder_quasar_open.svg",
  "folder_quasar": "assets/vscode-icons/icons/folder_quasar.svg",
  "folder_query_open": "assets/vscode-icons/icons/folder_query_open.svg",
  "folder_query": "assets/vscode-icons/icons/folder_query.svg",
  "folder_queries_open": "assets/vscode-icons/icons/folder_query_open.svg",
  "folder_queries": "assets/vscode-icons/icons/folder_query.svg",
  "folder_queue_open": "assets/vscode-icons/icons/folder_queue_open.svg",
  "folder_queue": "assets/vscode-icons/icons/folder_queue.svg",
  "folder_review_open": "assets/vscode-icons/icons/folder_review_open.svg",
  "folder_review": "assets/vscode-icons/icons/folder_review.svg",
  "folder_reviews_open": "assets/vscode-icons/icons/folder_review_open.svg",
  "folder_reviews": "assets/vscode-icons/icons/folder_review.svg",
  "folder_route_open": "assets/vscode-icons/icons/folder_route_open.svg",
  "folder_route": "assets/vscode-icons/icons/folder_route.svg",
  "folder_routes_open": "assets/vscode-icons/icons/folder_route_open.svg",
  "folder_routes": "assets/vscode-icons/icons/folder_route.svg",
  "folder_rules_open": "assets/vscode-icons/icons/folder_rules_open.svg",
  "folder_rules": "assets/vscode-icons/icons/folder_rules.svg",
  "folder_rust_open": "assets/vscode-icons/icons/folder_rust_open.svg",
  "folder_rust": "assets/vscode-icons/icons/folder_rust.svg",
  "folder_sass_open": "assets/vscode-icons/icons/folder_sass_open.svg",
  "folder_sass": "assets/vscode-icons/icons/folder_sass.svg",
  "folder_scala_open": "assets/vscode-icons/icons/folder_scala_open.svg",
  "folder_scala": "assets/vscode-icons/icons/folder_scala.svg",
  "folder_script_open": "assets/vscode-icons/icons/folder_script_open.svg",
  "folder_script": "assets/vscode-icons/icons/folder_script.svg",
  "folder_scripts_open": "assets/vscode-icons/icons/folder_script_open.svg",
  "folder_scripts": "assets/vscode-icons/icons/folder_script.svg",
  "folder_secure_open": "assets/vscode-icons/icons/folder_secure_open.svg",
  "folder_secure": "assets/vscode-icons/icons/folder_secure.svg",
  "folder_serverless_open":
      "assets/vscode-icons/icons/folder_serverless_open.svg",
  "folder_serverless": "assets/vscode-icons/icons/folder_serverless.svg",
  "folder_server_open": "assets/vscode-icons/icons/folder_server_open.svg",
  "folder_server": "assets/vscode-icons/icons/folder_server.svg",
  "folder_shared_open": "assets/vscode-icons/icons/folder_shared_open.svg",
  "folder_shared": "assets/vscode-icons/icons/folder_shared.svg",
  "folder_src_open": "assets/vscode-icons/icons/folder_src_open.svg",
  "folder_src": "assets/vscode-icons/icons/folder_src.svg",
  "folder_stack_open": "assets/vscode-icons/icons/folder_stack_open.svg",
  "folder_stack": "assets/vscode-icons/icons/folder_stack.svg",
  "folder_stencil_open": "assets/vscode-icons/icons/folder_stencil_open.svg",
  "folder_stencil": "assets/vscode-icons/icons/folder_stencil.svg",
  "folder_storage_open": "assets/vscode-icons/icons/folder_storage_open.svg",
  "folder_storage": "assets/vscode-icons/icons/folder_storage.svg",
  "folder_storybook_open":
      "assets/vscode-icons/icons/folder_storybook_open.svg",
  "folder_storybook": "assets/vscode-icons/icons/folder_storybook.svg",
  "folder_stylus_open": "assets/vscode-icons/icons/folder_stylus_open.svg",
  "folder_stylus": "assets/vscode-icons/icons/folder_stylus.svg",
  "folder_sublime_open": "assets/vscode-icons/icons/folder_sublime_open.svg",
  "folder_sublime": "assets/vscode-icons/icons/folder_sublime.svg",
  "folder_svelte_open": "assets/vscode-icons/icons/folder_svelte_open.svg",
  "folder_svelte": "assets/vscode-icons/icons/folder_svelte.svg",
  "folder": "assets/vscode-icons/icons/folder.svg",
  "folder_open": "assets/vscode-icons/icons/folder_open.svg",
  "folder_svg_open": "assets/vscode-icons/icons/folder_svg_open.svg",
  "folder_svg": "assets/vscode-icons/icons/folder_svg.svg",
  "folder_syntax_open": "assets/vscode-icons/icons/folder_syntax_open.svg",
  "folder_syntax": "assets/vscode-icons/icons/folder_syntax.svg",
  "folder_tasks_open": "assets/vscode-icons/icons/folder_tasks_open.svg",
  "folder_tasks": "assets/vscode-icons/icons/folder_tasks.svg",
  "folder_tauri_open": "assets/vscode-icons/icons/folder_tauri_open.svg",
  "folder_tauri": "assets/vscode-icons/icons/folder_tauri.svg",
  "folder_template_open": "assets/vscode-icons/icons/folder_template_open.svg",
  "folder_template": "assets/vscode-icons/icons/folder_template.svg",
  "folder_templates_open": "assets/vscode-icons/icons/folder_template_open.svg",
  "folder_templates": "assets/vscode-icons/icons/folder_template.svg",
  "folder_temp_open": "assets/vscode-icons/icons/folder_temp_open.svg",
  "folder_temp": "assets/vscode-icons/icons/folder_temp.svg",
  "folder_terraform_open":
      "assets/vscode-icons/icons/folder_terraform_open.svg",
  "folder_terraform": "assets/vscode-icons/icons/folder_terraform.svg",
  "folder_test_open": "assets/vscode-icons/icons/folder_test_open.svg",
  "folder_test": "assets/vscode-icons/icons/folder_test.svg",
  "folder_tests_open": "assets/vscode-icons/icons/folder_test_open.svg",
  "folder_tests": "assets/vscode-icons/icons/folder_test.svg",
  "folder_theme_open": "assets/vscode-icons/icons/folder_theme_open.svg",
  "folder_theme": "assets/vscode-icons/icons/folder_theme.svg",
  "folder_themes_open": "assets/vscode-icons/icons/folder_theme_open.svg",
  "folder_themes": "assets/vscode-icons/icons/folder_theme.svg",
  "folder_tool_open": "assets/vscode-icons/icons/folder_tools_open.svg",
  "folder_tool": "assets/vscode-icons/icons/folder_tools.svg",
  "folder_tools_open": "assets/vscode-icons/icons/folder_tools_open.svg",
  "folder_tools": "assets/vscode-icons/icons/folder_tools.svg",
  "folder_typescript_open":
      "assets/vscode-icons/icons/folder_typescript_open.svg",
  "folder_typescript": "assets/vscode-icons/icons/folder_typescript.svg",
  "folder_update_open": "assets/vscode-icons/icons/folder_update_open.svg",
  "folder_update": "assets/vscode-icons/icons/folder_update.svg",
  "folder_updates_open": "assets/vscode-icons/icons/folder_update_open.svg",
  "folder_updates": "assets/vscode-icons/icons/folder_update.svg",
  "folder_upload_open": "assets/vscode-icons/icons/folder_upload_open.svg",
  "folder_upload": "assets/vscode-icons/icons/folder_upload.svg",
  "folder_uploads_open": "assets/vscode-icons/icons/folder_upload_open.svg",
  "folder_uploads": "assets/vscode-icons/icons/folder_upload.svg",
  "folder_util_open": "assets/vscode-icons/icons/folder_utils_open.svg",
  "folder_util": "assets/vscode-icons/icons/folder_utils.svg",
  "folder_utils_open": "assets/vscode-icons/icons/folder_utils_open.svg",
  "folder_utils": "assets/vscode-icons/icons/folder_utils.svg",
  "folder_video_open": "assets/vscode-icons/icons/folder_video_open.svg",
  "folder_video": "assets/vscode-icons/icons/folder_video.svg",
  "folder_videos_open": "assets/vscode-icons/icons/folder_video_open.svg",
  "folder_videos": "assets/vscode-icons/icons/folder_video.svg",
  "folder_view_open": "assets/vscode-icons/icons/folder_view_open.svg",
  "folder_view": "assets/vscode-icons/icons/folder_view.svg",
  "folder_views_open": "assets/vscode-icons/icons/folder_view_open.svg",
  "folder_views": "assets/vscode-icons/icons/folder_view.svg",
  "folder_vm_open": "assets/vscode-icons/icons/folder_vm_open.svg",
  "folder_vm": "assets/vscode-icons/icons/folder_vm.svg",
  "folder_vscode_open": "assets/vscode-icons/icons/folder_vscode_open.svg",
  "folder_vscode": "assets/vscode-icons/icons/folder_vscode.svg",
  "folder_vuepress_open": "assets/vscode-icons/icons/folder_vuepress_open.svg",
  "folder_vuepress": "assets/vscode-icons/icons/folder_vuepress.svg",
  "folder_wakatime_open": "assets/vscode-icons/icons/folder_wakatime_open.svg",
  "folder_wakatime": "assets/vscode-icons/icons/folder_wakatime.svg",
  "folder_webpack_open": "assets/vscode-icons/icons/folder_webpack_open.svg",
  "folder_webpack": "assets/vscode-icons/icons/folder_webpack.svg",
  "folder_wordpress_open":
      "assets/vscode-icons/icons/folder_wordpress_open.svg",
  "folder_wordpress": "assets/vscode-icons/icons/folder_wordpress.svg",
  "font": "assets/vscode-icons/icons/font.svg",
  "forth": "assets/vscode-icons/icons/forth.svg",
  "fortran": "assets/vscode-icons/icons/fortran.svg",
  "foxpro": "assets/vscode-icons/icons/foxpro.svg",
  "fsharp": "assets/vscode-icons/icons/fsharp.svg",
  "fusebox": "assets/vscode-icons/icons/fusebox.svg",
  "gatsby": "assets/vscode-icons/icons/gatsby.svg",
  "gcp": "assets/vscode-icons/icons/gcp.svg",
  "gemfile": "assets/vscode-icons/icons/gemfile.svg",
  "gemini": "assets/vscode-icons/icons/gemini.svg",
  "gitpod": "assets/vscode-icons/icons/gitpod.svg",
  "git": "assets/vscode-icons/icons/git.svg",
  "godot-assets": "assets/vscode-icons/icons/godot-assets",
  "godot": "assets/vscode-icons/icons/godot.svg",
  "go-mod": "assets/vscode-icons/icons/go-mod",
  "go": "assets/vscode-icons/icons/go.svg",
  "gradle": "assets/vscode-icons/icons/gradle.svg",
  "grain": "assets/vscode-icons/icons/grain.svg",
  "graphcool": "assets/vscode-icons/icons/graphcool.svg",
  "graphql": "assets/vscode-icons/icons/graphql.svg",
  "gridsome": "assets/vscode-icons/icons/gridsome.svg",
  "groovy": "assets/vscode-icons/icons/groovy.svg",
  "grunt": "assets/vscode-icons/icons/grunt.svg",
  "gulp": "assets/vscode-icons/icons/gulp.svg",
  "hack": "assets/vscode-icons/icons/hack.svg",
  "haml": "assets/vscode-icons/icons/haml.svg",
  "handlebars": "assets/vscode-icons/icons/handlebars.svg",
  "haskell": "assets/vscode-icons/icons/haskell.svg",
  "haxe": "assets/vscode-icons/icons/haxe.svg",
  "hcl": "assets/vscode-icons/icons/hcl.svg",
  "helm": "assets/vscode-icons/icons/helm.svg",
  "heroku": "assets/vscode-icons/icons/heroku.svg",
  "hex": "assets/vscode-icons/icons/hex.svg",
  "horusec": "assets/vscode-icons/icons/horusec.svg",
  "hpp": "assets/vscode-icons/icons/hpp.svg",
  "h": "assets/vscode-icons/icons/h.svg",
  "html": "assets/vscode-icons/icons/html.svg",
  "http": "assets/vscode-icons/icons/http.svg",
  "husky": "assets/vscode-icons/icons/husky.svg",
  "hygen": "assets/vscode-icons/icons/hygen.svg",
  "i18n": "assets/vscode-icons/icons/i18n.svg",
  "idris": "assets/vscode-icons/icons/idris.svg",
  "image": "assets/vscode-icons/icons/image.svg",
  "imba": "assets/vscode-icons/icons/imba.svg",
  "ionic": "assets/vscode-icons/icons/ionic.svg",
  "istanbul": "assets/vscode-icons/icons/istanbul.svg",
  "jar": "assets/vscode-icons/icons/jar.svg",
  "javaclass": "assets/vscode-icons/icons/javaclass.svg",
  "java": "assets/vscode-icons/icons/java.svg",
  "jenkins": "assets/vscode-icons/icons/jenkins.svg",
  "jest": "assets/vscode-icons/icons/jest.svg",
  "jinja": "assets/vscode-icons/icons/jinja.svg",
  "jsconfig": "assets/vscode-icons/icons/jsconfig.svg",
  "jsmap": "assets/vscode-icons/icons/jsmap.svg",
  "json": "assets/vscode-icons/icons/json.svg",
  "jsp": "assets/vscode-icons/icons/jsp.svg",
  "js": "assets/vscode-icons/icons/js.svg",
  "julia": "assets/vscode-icons/icons/julia.svg",
  "jupyter": "assets/vscode-icons/icons/jupyter.svg",
  "karma": "assets/vscode-icons/icons/karma.svg",
  "key": "assets/vscode-icons/icons/key.svg",
  "kivy": "assets/vscode-icons/icons/kivy.svg",
  "kl": "assets/vscode-icons/icons/kl.svg",
  "kotlin": "assets/vscode-icons/icons/kotlin.svg",
  "kusto": "assets/vscode-icons/icons/kusto.svg",
  "lerna": "assets/vscode-icons/icons/lerna.svg",
  "less": "assets/vscode-icons/icons/less.svg",
  "lib": "assets/vscode-icons/icons/lib.svg",
  "lighthouse": "assets/vscode-icons/icons/lighthouse.svg",
  "lilypond": "assets/vscode-icons/icons/lilypond.svg",
  "liquid": "assets/vscode-icons/icons/liquid.svg",
  "lisp": "assets/vscode-icons/icons/lisp.svg",
  "livescript": "assets/vscode-icons/icons/livescript.svg",
  "llvm": "assets/vscode-icons/icons/llvm.svg",
  "lock": "assets/vscode-icons/icons/lock.svg",
  "log": "assets/vscode-icons/icons/log.svg",
  "lolcode": "assets/vscode-icons/icons/lolcode.svg",
  "lua": "assets/vscode-icons/icons/lua.svg",
  "makefile": "assets/vscode-icons/icons/makefile.svg",
  "markdown": "assets/vscode-icons/icons/markdown.svg",
  "markojs": "assets/vscode-icons/icons/markojs.svg",
  "mathematica": "assets/vscode-icons/icons/mathematica.svg",
  "matlab": "assets/vscode-icons/icons/matlab.svg",
  "maven": "assets/vscode-icons/icons/maven.svg",
  "mdx": "assets/vscode-icons/icons/mdx.svg",
  "merlin": "assets/vscode-icons/icons/merlin.svg",
  "meson": "assets/vscode-icons/icons/meson.svg",
  "minecraft": "assets/vscode-icons/icons/minecraft.svg",
  "mint": "assets/vscode-icons/icons/mint.svg",
  "mjml": "assets/vscode-icons/icons/mjml.svg",
  "mocha": "assets/vscode-icons/icons/mocha.svg",
  "modernizr": "assets/vscode-icons/icons/modernizr.svg",
  "moonscript": "assets/vscode-icons/icons/moonscript.svg",
  "mxml": "assets/vscode-icons/icons/mxml.svg",
  "ndst": "assets/vscode-icons/icons/ndst.svg",
  "nestjs": "assets/vscode-icons/icons/nestjs.svg",
  "netlify": "assets/vscode-icons/icons/netlify.svg",
  "next": "assets/vscode-icons/icons/next.svg",
  "nginx": "assets/vscode-icons/icons/nginx.svg",
  "nim": "assets/vscode-icons/icons/nim.svg",
  "nix": "assets/vscode-icons/icons/nix.svg",
  "nodejs": "assets/vscode-icons/icons/nodejs.svg",
  "nodemon": "assets/vscode-icons/icons/nodemon.svg",
  "npm": "assets/vscode-icons/icons/npm.svg",
  "nrwl": "assets/vscode-icons/icons/nrwl.svg",
  "nuget": "assets/vscode-icons/icons/nuget.svg",
  "nunjucks": "assets/vscode-icons/icons/nunjucks.svg",
  "nuxt": "assets/vscode-icons/icons/nuxt.svg",
  "ocaml": "assets/vscode-icons/icons/ocaml.svg",
  "odin": "assets/vscode-icons/icons/odin.svg",
  "opam": "assets/vscode-icons/icons/opam.svg",
  "opa": "assets/vscode-icons/icons/opa.svg",
  "opengl": "assets/vscode-icons/icons/opengl.svg",
  "pascal": "assets/vscode-icons/icons/pascal.svg",
  "pawn": "assets/vscode-icons/icons/pawn.svg",
  "pdf": "assets/vscode-icons/icons/pdf.svg",
  "percy": "assets/vscode-icons/icons/percy.svg",
  "perl": "assets/vscode-icons/icons/perl.svg",
  "photoshop": "assets/vscode-icons/icons/photoshop.svg",
  "php-cs-fixer": "assets/vscode-icons/icons/php-cs",
  "php": "assets/vscode-icons/icons/php.svg",
  "phpunit": "assets/vscode-icons/icons/phpunit.svg",
  "pipeline": "assets/vscode-icons/icons/pipeline.svg",
  "playwright": "assets/vscode-icons/icons/playwright.svg",
  "pnpm": "assets/vscode-icons/icons/pnpm.svg",
  "postcssconfig": "assets/vscode-icons/icons/postcssconfig.svg",
  "posthtml": "assets/vscode-icons/icons/posthtml.svg",
  "powerpoint": "assets/vscode-icons/icons/powerpoint.svg",
  "powershell": "assets/vscode-icons/icons/powershell.svg",
  "prettier": "assets/vscode-icons/icons/prettier.svg",
  "prisma": "assets/vscode-icons/icons/prisma.svg",
  "processing": "assets/vscode-icons/icons/processing.svg",
  "prolog": "assets/vscode-icons/icons/prolog.svg",
  "proto": "assets/vscode-icons/icons/proto.svg",
  "protractor": "assets/vscode-icons/icons/protractor.svg",
  "pug": "assets/vscode-icons/icons/pug.svg",
  "puppet": "assets/vscode-icons/icons/puppet.svg",
  "purescript": "assets/vscode-icons/icons/purescript.svg",
  "python-misc": "assets/vscode-icons/icons/python-misc",
  "python": "assets/vscode-icons/icons/python.svg",
  "qsharp": "assets/vscode-icons/icons/qsharp.svg",
  "quasar": "assets/vscode-icons/icons/quasar.svg",
  "racket": "assets/vscode-icons/icons/racket.svg",
  "raml": "assets/vscode-icons/icons/raml.svg",
  "razor": "assets/vscode-icons/icons/razor.svg",
  "react": "assets/vscode-icons/icons/react.svg",
  "reactts": "assets/vscode-icons/icons/reactts.svg",
  "readme": "assets/vscode-icons/icons/readme.svg",
  "reason": "assets/vscode-icons/icons/reason.svg",
  "red": "assets/vscode-icons/icons/red.svg",
  "remix": "assets/vscode-icons/icons/remix.svg",
  "renovate": "assets/vscode-icons/icons/renovate.svg",
  "replit": "assets/vscode-icons/icons/replit.svg",
  "rescript": "assets/vscode-icons/icons/rescript.svg",
  "restql": "assets/vscode-icons/icons/restql.svg",
  "riot": "assets/vscode-icons/icons/riot.svg",
  "roadmap": "assets/vscode-icons/icons/roadmap.svg",
  "robots": "assets/vscode-icons/icons/robots.svg",
  "rollup": "assets/vscode-icons/icons/rollup.svg",
  "rome": "assets/vscode-icons/icons/rome.svg",
  "routing": "assets/vscode-icons/icons/routing.svg",
  "r": "assets/vscode-icons/icons/r.svg",
  "rubocop": "assets/vscode-icons/icons/rubocop.svg",
  "ruby": "assets/vscode-icons/icons/ruby.svg",
  "rust": "assets/vscode-icons/icons/rust.svg",
  "san": "assets/vscode-icons/icons/san.svg",
  "sass": "assets/vscode-icons/icons/sass.svg",
  "sas": "assets/vscode-icons/icons/sas.svg",
  "sbt": "assets/vscode-icons/icons/sbt.svg",
  "scala": "assets/vscode-icons/icons/scala.svg",
  "scheme": "assets/vscode-icons/icons/scheme.svg",
  "search": "assets/vscode-icons/icons/search.svg",
  "semantic-release": "assets/vscode-icons/icons/semantic-release",
  "sentry": "assets/vscode-icons/icons/sentry.svg",
  "sequelize": "assets/vscode-icons/icons/sequelize.svg",
  "serverless": "assets/vscode-icons/icons/serverless.svg",
  "settings": "assets/vscode-icons/icons/settings.svg",
  "shaderlab": "assets/vscode-icons/icons/shaderlab.svg",
  "siyuan": "assets/vscode-icons/icons/siyuan.svg",
  "sketch": "assets/vscode-icons/icons/sketch.svg",
  "slim": "assets/vscode-icons/icons/slim.svg",
  "slug": "assets/vscode-icons/icons/slug.svg",
  "smarty": "assets/vscode-icons/icons/smarty.svg",
  "sml": "assets/vscode-icons/icons/sml.svg",
  "snowpack": "assets/vscode-icons/icons/snowpack.svg",
  "snyk": "assets/vscode-icons/icons/snyk.svg",
  "solidity": "assets/vscode-icons/icons/solidity.svg",
  "steadybit": "assets/vscode-icons/icons/steadybit.svg",
  "stencil": "assets/vscode-icons/icons/stencil.svg",
  "stitches": "assets/vscode-icons/icons/stitches.svg",
  "storybook": "assets/vscode-icons/icons/storybook.svg",
  "stryker": "assets/vscode-icons/icons/stryker.svg",
  "stylelint": "assets/vscode-icons/icons/stylelint.svg",
  "stylus": "assets/vscode-icons/icons/stylus.svg",
  "sublime": "assets/vscode-icons/icons/sublime.svg",
  "svelte": "assets/vscode-icons/icons/svelte.svg",
  "svgo": "assets/vscode-icons/icons/svgo.svg",
  "svgr": "assets/vscode-icons/icons/svgr.svg",
  "svg": "assets/vscode-icons/icons/svg.svg",
  "swc": "assets/vscode-icons/icons/swc.svg",
  "swift": "assets/vscode-icons/icons/swift.svg",
  "table": "assets/vscode-icons/icons/table.svg",
  "tailwind": "assets/vscode-icons/icons/tailwind.svg",
  "tauri": "assets/vscode-icons/icons/tauri.svg",
  "tcl": "assets/vscode-icons/icons/tcl.svg",
  "teal": "assets/vscode-icons/icons/teal.svg",
  "template": "assets/vscode-icons/icons/template.svg",
  "terraform": "assets/vscode-icons/icons/terraform.svg",
  "testjs": "assets/vscode-icons/icons/testjs.svg",
  "testjsx": "assets/vscode-icons/icons/testjsx.svg",
  "testts": "assets/vscode-icons/icons/testts.svg",
  "tex": "assets/vscode-icons/icons/tex.svg",
  "textlint": "assets/vscode-icons/icons/textlint.svg",
  "tobimake": "assets/vscode-icons/icons/tobimake.svg",
  "tobi": "assets/vscode-icons/icons/tobi.svg",
  "todo": "assets/vscode-icons/icons/todo.svg",
  "travis": "assets/vscode-icons/icons/travis.svg",
  "tsconfig": "assets/vscode-icons/icons/tsconfig.svg",
  "turborepo": "assets/vscode-icons/icons/turborepo.svg",
  "twig": "assets/vscode-icons/icons/twig.svg",
  "twine": "assets/vscode-icons/icons/twine.svg",
  "typescriptdef": "assets/vscode-icons/icons/typescriptdef.svg",
  "typescript": "assets/vscode-icons/icons/typescript.svg",
  "uml": "assets/vscode-icons/icons/uml.svg",
  "url": "assets/vscode-icons/icons/url.svg",
  "vagrant": "assets/vscode-icons/icons/vagrant.svg",
  "vala": "assets/vscode-icons/icons/vala.svg",
  "velocity": "assets/vscode-icons/icons/velocity.svg",
  "vercel": "assets/vscode-icons/icons/vercel.svg",
  "verilog": "assets/vscode-icons/icons/verilog.svg",
  "vfl": "assets/vscode-icons/icons/vfl.svg",
  "video": "assets/vscode-icons/icons/video.svg",
  "vim": "assets/vscode-icons/icons/vim.svg",
  "virtual": "assets/vscode-icons/icons/virtual.svg",
  "visualstudio": "assets/vscode-icons/icons/visualstudio.svg",
  "vitest": "assets/vscode-icons/icons/vitest.svg",
  "vite": "assets/vscode-icons/icons/vite.svg",
  "vlang": "assets/vscode-icons/icons/vlang.svg",
  "vscode": "assets/vscode-icons/icons/vscode.svg",
  "vue-config": "assets/vscode-icons/icons/vue-config",
  "vue": "assets/vscode-icons/icons/vue.svg",
  "wakatime": "assets/vscode-icons/icons/wakatime.svg",
  "wallaby": "assets/vscode-icons/icons/wallaby.svg",
  "watchman": "assets/vscode-icons/icons/watchman.svg",
  "webassembly": "assets/vscode-icons/icons/webassembly.svg",
  "webhint": "assets/vscode-icons/icons/webhint.svg",
  "webpack": "assets/vscode-icons/icons/webpack.svg",
  "windicss": "assets/vscode-icons/icons/windicss.svg",
  "wolframlanguage": "assets/vscode-icons/icons/wolframlanguage.svg",
  "word": "assets/vscode-icons/icons/word.svg",
  "xaml": "assets/vscode-icons/icons/xaml.svg",
  "xml": "assets/vscode-icons/icons/xml.svg",
  "yaml": "assets/vscode-icons/icons/yaml.svg",
  "yang": "assets/vscode-icons/icons/yang.svg",
  "yarn": "assets/vscode-icons/icons/yarn.svg",
  "zig": "assets/vscode-icons/icons/zig.svg",
  "zip": "assets/vscode-icons/icons/zip.svg",
};

const _video = [
  "3g2",
  "3gp",
  "asf",
  "amv",
  "avi",
  "divx",
  "qt",
  "f4a",
  "f4b",
  "f4p",
  "f4v",
  "flv",
  "m2v",
  "m4v",
  "mkv",
  "mk3d",
  "mov",
  "mp2",
  "mp4",
  "mpe",
  "mpeg",
  "mpeg2",
  "mpg",
  "mpv",
  "nsv",
  "ogv",
  "rm",
  "rmvb",
  "svi",
  "vob",
  "webm",
  "wmv",
];
const _audio = [
  "aac",
  "act",
  "aiff",
  "amr",
  "ape",
  "au",
  "dct",
  "dss",
  "dvf",
  "flac",
  "gsm",
  "iklax",
  "ivs",
  "m4a",
  "m4b",
  "m4p",
  "mmf",
  "mogg",
  "mp3",
  "mpc",
  "msv",
  "oga",
  "ogg",
  "opus",
  "ra",
  "raw",
  "tta",
  "vox",
  "wav",
  "wma",
];
const _image = ["jpeg", "jpg", "gif", "png", "bmp", "tiff", "ico"];
const _font = ["woff", "woff2", "ttf", "otf", "eot", "pfa", "pfb", "sfd"];

vscodeIconsCompute() {
  for (var name in _video) {
    vscodeIconsValid[name] = vscodeIconsValid["video"]!;
  }
  for (var name in _audio) {
    vscodeIconsValid[name] = vscodeIconsValid["audio"]!;
  }
  for (var name in _image) {
    vscodeIconsValid[name] = vscodeIconsValid["image"]!;
  }
  for (var name in _font) {
    vscodeIconsValid[name] = vscodeIconsValid["font"]!;
  }
}
